"""restaurant_staff_null_safe_uniqueness

Revision ID: 8e9dbef6577d
Revises: 91b9633d792d
Create Date: 2026-10-02 00:17:02.034777
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '8e9dbef6577d'
down_revision: Union[str, Sequence[str], None] = '91b9633d792d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_staff') as batch_op:
        batch_op.drop_constraint(op.f('uq_restaurant_staff_restaurant_id'), type_='unique')
    op.create_index('uq_restaurant_staff_branch_member', 'restaurant_staff', ['restaurant_id', 'user_id', 'branch_id'], unique=True, sqlite_where=sa.text('branch_id IS NOT NULL'), postgresql_where=sa.text('branch_id IS NOT NULL'))
    op.create_index('uq_restaurant_staff_global_member', 'restaurant_staff', ['restaurant_id', 'user_id'], unique=True, sqlite_where=sa.text('branch_id IS NULL'), postgresql_where=sa.text('branch_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_restaurant_staff_global_member', table_name='restaurant_staff', sqlite_where=sa.text('branch_id IS NULL'), postgresql_where=sa.text('branch_id IS NULL'))
    op.drop_index('uq_restaurant_staff_branch_member', table_name='restaurant_staff', sqlite_where=sa.text('branch_id IS NOT NULL'), postgresql_where=sa.text('branch_id IS NOT NULL'))
    with op.batch_alter_table('restaurant_staff') as batch_op:
        batch_op.create_unique_constraint(op.f('uq_restaurant_staff_restaurant_id'), ['restaurant_id', 'user_id', 'branch_id'])
    # ### end Alembic commands ###
