"""customer_default_address_uniqueness

Revision ID: e8e1cb5f1505
Revises: 8e9dbef6577d
Create Date: 2026-10-02 00:40:06.111291
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'e8e1cb5f1505'
down_revision: Union[str, Sequence[str], None] = '8e9dbef6577d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_addresses_one_default_per_user', 'addresses', ['user_id'], unique=True, sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_addresses_one_default_per_user', table_name='addresses', sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default = true'))
    # ### end Alembic commands ###
